# Generated by Django 4.0.4 on 2022-06-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('string', models.CharField(max_length=200, unique=True, verbose_name='Оригинальная строка')),
                ('length', models.IntegerField(verbose_name='Длинна строки')),
            ],
            options={
                'verbose_name': 'Оригинал строки',
                'verbose_name_plural': 'Оригиналы строк',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='UserID')),
                ('name', models.CharField(max_length=255, verbose_name='Telegram Имя пользователя')),
                ('user_rate', models.IntegerField(verbose_name='Рейтинг пользователя')),
            ],
            options={
                'verbose_name': 'Телеграм Юзер',
                'verbose_name_plural': 'Телеграм Юзеры',
            },
        ),
        migrations.CreateModel(
            name='YandexTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('translate', models.CharField(max_length=200, verbose_name='Перевод от Yandex')),
                ('length', models.IntegerField(verbose_name='Длинна строки')),
                ('yandex_score', models.IntegerField(verbose_name='Баллы Yandex')),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_yandex', to='app.originalstring', verbose_name='Оригинал')),
            ],
            options={
                'verbose_name': 'Первеод от Yandex',
                'verbose_name_plural': 'Переводы от Yandex',
            },
        ),
        migrations.CreateModel(
            name='TatsoftTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('translate', models.CharField(max_length=200, verbose_name='Перевод от Tatsoft')),
                ('length', models.IntegerField(verbose_name='Длинна строки')),
                ('tatsoft_score', models.IntegerField(verbose_name='Баллы Tatsoft')),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_tatsoft', to='app.originalstring', verbose_name='Оригинал')),
            ],
            options={
                'verbose_name': 'Первеод от Tatsoft',
                'verbose_name_plural': 'Переводы от Tatsoft',
            },
        ),
        migrations.CreateModel(
            name='GoogleTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('translate', models.CharField(max_length=200, verbose_name='Перевод от Google')),
                ('length', models.IntegerField(verbose_name='Длинна строки')),
                ('google_score', models.IntegerField(verbose_name='Баллы Google')),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_google', to='app.originalstring', verbose_name='Оригинал')),
            ],
            options={
                'verbose_name': 'Первеод от Google',
                'verbose_name_plural': 'Переводы от Google',
            },
        ),
    ]
